from playwright.sync_api import Page


def test_task1_get_by_role(page: Page):
    page.goto('https://the-internet.herokuapp.com/')
    page.get_by_role('link', name='Form Authentication').click()
    page.get_by_role('textbox', name='username').fill('Test User')
    page.get_by_role('textbox', name='password').fill('Password123')
    page.get_by_role('button', name='Login').click()


def test_for_demo(page: Page):
    page.goto('https://demoqa.com/automation-practice-form')
    first_name = page.get_by_placeholder('First Name')
    first_name.fill('Джонни')
    last_name = page.get_by_placeholder('Last Name')
    last_name.fill('Депп')
    email = page.locator('#userEmail')
    email.fill('test@mail.ru')
    gender = page.locator('//*[text()="Male"]')
    gender.check()
    mobile = page.get_by_placeholder('Mobile Number')
    mobile.fill('8961478963')
    date_of_birth = page.locator('#dateOfBirthInput')
    date_of_birth.click()
    month = page.locator('.react-datepicker__month-select')
    month.select_option('5')
    year = page.locator('.react-datepicker__year-select')
    year.select_option('1963')
    day = page.locator('//*[@aria-label="Choose Sunday, June 9th, 1963"]')
    day.click()
    subjects = page.locator("#subjectsInput")
    subjects.fill("Arts")
    subjects.press("Tab")
    hobbies = page.locator('//*[text()="Music"]')
    hobbies.check()
    address = page.get_by_placeholder('Current Address')
    address.fill('USA')
    state = page.locator('#state')
    state.click()
    state = page.locator('//*[text()="Haryana"]')
    state.click()
    city = page.locator('#city')
    city.click()
    city = page.locator('//*[text()="Karnal"]')
    city.click()
    submit_btn = page.get_by_text('Submit')
    submit_btn.click()
